_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("textocr_train_pos","syntext1_poly_train_pos", "syntext2_poly_train_pos", "lsvt_poly_train_pos", "art_poly_train_rotate_pos", "lsvt_poly_train_pos", "art_poly_train_rotate_pos",)
  TEST: ("art_test",)

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 2000
  STEPS: (180000,)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 5000000  # no evaluation

OUTPUT_DIR: "output/r_50_poly/pretrain_art"