_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",) #totaltext_poly_train_pos, totaltext_poly_train_rotate_pos
  TEST: ("totaltext_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  WEIGHTS: "/home/duolun/.torch/iopath_cache/detectron2/ImageNetPretrained/torchvision/swin_small_patch4_window7_224_convert.pth"
  TRANSFORMER:
    STRIDES: [8, 16, 32]
    NUM_CHANNELS: [192, 384, 768]

 #
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 2000
  STEPS: (70000,)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/swin_s/totaltext/npre"