_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",) #totaltext_poly_train_pos, totaltext_poly_train_rotate_pos
  TEST: ("totaltext_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  #WEIGHTS: "./output/r_50_poly/totaltext/npre/model_0047999.pth"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 2000
  STEPS: (70000,)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/r_50_poly/totaltext/npre"