_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",) #totaltext_poly_train_pos, totaltext_poly_train_rotate_pos
  TEST: ("totaltext_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  BACKBONE:
    NAME: "build_resnet_vd_backbone"
  WEIGHTS: "/home/duolun/.torch/iopath_cache/detectron2/ImageNetPretrained/torchvision/resnet50d_ra2-464e36ba.pkl"
  RESNETS:
    DEFORM_ON_PER_STAGE: [ False, False, True, True ] # dcn on res4, res5
    OUT_FEATURES: ["res3", "res4", "res5"]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 2000
  STEPS: (70000,)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "output/rvd_50_poly/totaltext/npre"