_BASE_: "../Base.yaml"

DATASETS:
  #TRAIN: ("syntext1_poly_train_pos", "syntext2_poly_train_pos", "mlt_poly_train_pos", "totaltext_poly_train_pos",)
  #TRAIN: ("textocr_train_pos", "syntext1_poly_train_pos", "syntext2_poly_train_pos", "mlt_poly_train_pos", "totaltext_poly_train_rotate_pos","ctw1500_poly_train_rotate_pos", "totaltext_poly_train_rotate_pos","ctw1500_poly_train_rotate_pos")
  TRAIN: ("textocr_train_pos", "syntext1_poly_train_pos", "syntext2_poly_train_pos", "totaltext_poly_train_rotate_pos")
  TEST: ("totaltext_poly_test",)

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 2000
  STEPS: (180000,)
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 5000

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "output/r_50_poly/pretrain"