_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",)
  TEST: ("totaltext_poly_test",)  # or "inversetext_test", "totaltext_poly_test_rotate"

MODEL:
  BACKBONE:
    NAME: "build_resnet_vd_backbone"
  WEIGHTS: "output/rvd_50_poly/totaltext/pretrain/model_final.pth"
  RESNETS:
    DEFORM_ON_PER_STAGE: [ False, False, True, True ] # dcn on res4, res5
    OUT_FEATURES: ["res3", "res4", "res5"]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (20000,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 500

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "output/rvd_50_poly/totaltext/finetune"