_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("ctw1500_poly_train_rotate_pos",)
  TEST: ("ctw1500_poly_test",)

MODEL:
  WEIGHTS: "output/rvd_50_poly/ctw1500/pretrain/model_0199999.pth" #output/rvd_50_poly/ctw1500/pretrain/model_0199999.pth

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (2000,)
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 500

INPUT:
  MIN_SIZE_TEST: 960
  MAX_SIZE_TEST: 1280

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: "output/r_50_poly/ctw1500/finetune"
